baseURL = 'https://blog.madcodelife.me/'
languageCode = 'zh-CN'
title = '😡'
theme = 'PaperMod'

[params]
comments = true

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 3
