baseURL: https://madcodelife.com/
languageCode: zh-CN
title: Digital Notes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: G-N5DMQTRN38

minify:
  disableXML: true
  minifyOutput: true

params:
  description: Floyd Wang 的博客
  author: Floyd Wang
  keywords: [blog, page, Floyd Wang, madcodelife, 博客，技术，分享]

  defaultTheme: auto
  env: production
  comments: true

  ShowReadingTime: false
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: 📒
    Content: >
      **数字备忘录**，用文字记录下不成熟的想法。

  socialIcons:
    - name: github
      url: https://github.com/madcodelife
    - name: twitter
      url: https://twitter.com/madcodelife

  assets:
    disableHLJS: true
    favicon: https://p.madcodelife.com/blog/2024/03/7b4723ad2e5e79d56e4ae63f9d1531c6.ico
    favicon16x16: https://p.madcodelife.com/blog/2024/03/6ce2e8139f919707100767e752dee588.png
    favicon32x32: https://p.madcodelife.com/blog/2024/03/7b8d7f7dcb90248a69769d8c8bf258ee.png
    apple_touch_icon: https://p.madcodelife.com/blog/2024/03/31b32fa6e764e6e35bf21a33430773cc.png
    safari_pinned_tab: https://p.madcodelife.com/blog/2024/03/31b32fa6e764e6e35bf21a33430773cc.png

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

taxonomies:
  tag: tags
  category: categories

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: search
      name: Search
      url: /search/
      weight: 3
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
