DefaultContentLanguage = "zh-cn"
author = "Floyd Wang"
baseURL = "https://madcodelife.com/"
languageCode = "zh-CN"
theme = "hugo-bearblog"
title = "11011"

enableInlineShortcodes = true
enableRobotsTXT = true

[pagination]
pagerSize = 10

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "越努力越幸运"
googleAnalytics = "G-N5DMQTRN38"
images = [
  'https://assets.madcodelife.com/blog/2024/11/af2307cfa5771e2e599f7d1fc7535982.jpeg',
]

[params.giscus]
category = 'General'
categoryId = 'DIC_kwDOImHxVs4CemCQ'
emitMetadata = "0"
inputPosition = 'bottom'
lang = 'zh-CN'
mapping = 'title'
reactionsEnabled = "1"
repo = 'madcodelife/madcodelife.github.io'
repoId = 'R_kgDOImHxVg'
strict = "0"
theme = 'preferred_color_scheme'

[markup]
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = false
style = 'friendly'
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
