DefaultContentLanguage = "zh-cn"
author = "Floyd Wang"
baseURL = "https://madcodelife.com/"
languageCode = "zh-CN"
paginate = 10
theme = "hugo-bearblog"
title = "Digital Notes"

enableInlineShortcodes = true
enableRobotsTXT = true

googleAnalytics = "G-N5DMQTRN38"

[params]
description = "越努力越幸运"

[params.giscus]
category = 'General'
categoryId = 'DIC_kwDOImHxVs4CemCQ'
emitMetadata = "0"
inputPosition = 'bottom'
lang = 'zh-CN'
mapping = 'title'
reactionsEnabled = "1"
repo = 'madcodelife/madcodelife.github.io'
repoId = 'R_kgDOImHxVg'
strict = "0"
theme = 'preferred_color_scheme'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
